# Generated by Django 5.2.5 on 2025-09-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='recommendations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='remedies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='symptoms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='file',
            field=models.FileField(default=1, upload_to='analyses/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analysis',
            name='result',
            field=models.TextField(blank=True, null=True),
        ),
    ]
